services:
  atlantis:
    image: ghcr.io/runatlantis/atlantis:latest
    container_name: atlantis
    environment:
      ATLANTIS_GH_APP_ID: ${ATLANTIS_GH_APP_ID}
      ATLANTIS_GH_APP_KEY: ${ATLANTIS_GH_APP_KEY}
      ATLANTIS_GH_WEBHOOK_SECRET: ${ATLANTIS_GH_WEBHOOK_SECRET}
      ATLANTIS_PORT: ${ATLANTIS_PORT}
      ATLANTIS_REPO_ALLOWLIST: ${ATLANTIS_REPO_ALLOWLIST}
      ATLANTIS_WRITE_GIT_CREDS: "true"
      ATLANTIS_REPO_CONFIG: /etc/atlantis/repos.yaml
      TF_VAR_SERVER_USER: ${TF_VAR_SERVER_USER}
      TF_VAR_SERVER_HOST: ${TF_VAR_SERVER_HOST}
      TF_VAR_GF_SECURITY_ADMIN_USER: ${TF_VAR_GF_SECURITY_ADMIN_USER}
      TF_VAR_GF_SECURITY_ADMIN_PASSWORD: ${TF_VAR_GF_SECURITY_ADMIN_PASSWORD}
    network_mode: host
    volumes:
      - ~/.ssh/atlantis_id_rsa:/home/atlantis/.ssh/id_rsa:ro
      - atlantis-data:/home/atlantis/.atlantis
      - ./repos.yaml:/etc/atlantis/repos.yaml:ro
    restart: unless-stopped

volumes:
  atlantis-data:
